apiVersion: v1
entries:
  net-expose:
  - apiVersion: v2
    appVersion: ssh-0.1.0
    created: "2020-07-09T11:48:05.945759+03:00"
    description: Expose your Kubernetes resources to the world!
    digest: bd60f1cb10cd00195b4cf1d574ad6dc3062fbfdbe31a8bc38f4e4eb5310ebc70
    name: net-expose
    type: application
    urls:
    - net-expose-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: ssh-0.1.0
    created: "2020-07-09T11:48:05.945359+03:00"
    description: Expose your Kubernetes resources to the world!
    digest: 167bb9aa563c24841a95ba63b3f2e3907c332a5415328160bf9ba27203e56d3f
    name: net-expose
    type: application
    urls:
    - net-expose-0.2.0.tgz
    version: 0.2.0
generated: "2020-07-09T11:48:05.944169+03:00"
