image:
  repository: operatorequals/k8s-net-expose
  tag: ssh-0.1.0
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

ssh:
  host: 
  port: 22
  user: root
  # set SSH key using Helm --set-file
  key: /path/to/id_rsa

  # The remote port that will accept and tunnel connections to
  # the exposed Kubernetes resource

  # To attach to a <1024, SSH user must have root privileges
remotePort: 8000

  # By default net-expose tries to expose the K8s dashboard
  # often deployed in Minikube builds.
k8sExportService:
  name: kubernetes-dashboard
  port: 80

  # If set to 'true' an initContainer is spawned to enable the
  # OpenSSH Server "GatewayPorts" option and restart the remote
  # sshd service.
gatewayports:
  enable: false
  image: operatorequals/k8s-net-expose-gatewayports:0.1.0


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
